// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMceLuB2DCR29Oqx5YZYkLPAAKBEfSNfA',
    appId: '1:376197965339:web:6b5f9afdf38c9d63e4babe',
    messagingSenderId: '376197965339',
    projectId: 'pawd-todo',
    authDomain: 'pawd-todo.firebaseapp.com',
    storageBucket: 'pawd-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtK7bAB7Yo_ohR7OlmVxFhmdfX9WxppQ',
    appId: '1:376197965339:android:95af3cf29dede025e4babe',
    messagingSenderId: '376197965339',
    projectId: 'pawd-todo',
    storageBucket: 'pawd-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARc-9Gewxweeg68bn03Dse2BklW0rwHZI',
    appId: '1:376197965339:ios:06b7677d0eec7cdde4babe',
    messagingSenderId: '376197965339',
    projectId: 'pawd-todo',
    storageBucket: 'pawd-todo.appspot.com',
    iosClientId: '376197965339-pue8uc50didjn7sn2h8pgvunjgj035b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARc-9Gewxweeg68bn03Dse2BklW0rwHZI',
    appId: '1:376197965339:ios:06b7677d0eec7cdde4babe',
    messagingSenderId: '376197965339',
    projectId: 'pawd-todo',
    storageBucket: 'pawd-todo.appspot.com',
    iosClientId: '376197965339-pue8uc50didjn7sn2h8pgvunjgj035b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawd',
  );
}
